import type { Metadata } from "next";
import "../globals.css";
import Nav from "@/components/Nav"
import Footer from "@/components/Footer";
import Customizer from "@/components/Customizer";
import {Providers} from "../providers";

export const metadata: Metadata = {
  title: "about",
  description: "Generated by create next app",
};

export default function About
({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

          <div className="w-[92%] flex flex-row justify-between">
            <Nav/>
            <div className="w-[100%] flex justify-center">
            {children}
            </div>
            <Providers>
            <div className="fixed top-5 right-5">  
            <Customizer/>
            </div>
            </Providers>
          </div>
           
      </body>
    </html>
  );
}
