import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav"
import Footer from "@/components/Footer";
import {Providers} from "./providers";
//import About from "./(about)/page";

export const metadata: Metadata = {
  title: "y e a b s i r a",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

          <div className="w-[92%] flex flex-row justify-center items-center">
            <Nav/>
            {children}
          </div>
          <Footer/>

      </body>
    </html>
  );
}
