import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav"
import Footer from "@/components/Footer";
import Customizer from "@/components/Customizer";
import {Providers} from "./providers";

export const metadata: Metadata = {
  title: "y e a b s i r a",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

          <div className="w-[92%] flex flex-row justify-between">
            <Nav/>
            {children}
            <Providers>
            <div className="fixed top-5 right-5">  
            <Customizer/>
            </div>
            </Providers>
          </div>
 
          <Footer/>

      </body>
    </html>
  );
}
